-- Pre-aggregated on-hand inventory at SKU x week grain + pallet dims.
-- Source: DQ_EQ_WITH_KEYS03 (1M+ rows). Use for pivot/SKU/pallet drill — no app queries to source.
-- PALLET_SOURCE: per-pallet classification (FROM PRODUCTION | FROM REPACK). On tie (R=P), default to REPACK.
--   based on NET_CARTONS_R vs NET_CARTONS_P; RUN_TYPE derived for filter compatibility.
-- Created in DBT_DEV_DBT_DEV. Dev: target_lag 15 min (~3500 rows). Prod: '5 minutes'.
CREATE OR REPLACE DYNAMIC TABLE FROSTY.DBT_DEV_DBT_DEV.DT_INV_ON_HAND_SKU_GRAIN(
  GROUP_CATEGORY, FINAL_STAGE_STATUS, VARIETY_ABBR, SKU, WEEK_BUCKET, WEEK_BUCKET_NUM,
  PACK_ABBR, GRADE_ABBR, SIZE_ABBR, POOL, "Process Code",
  GROWER_NUMBER, PALLET_TR_CODE, PALLET_TICKET, "CROP_YEAR", PALLET_SOURCE_FLAG, RUN_TYPE,
  CARTONS, EQ_ON_HAND, CARTONS_AVAIL
) target_lag = '15 minutes' refresh_mode = AUTO initialize = ON_SCHEDULE warehouse = CT_WH
AS
WITH inv_base AS (
  SELECT
    GROUP_CATEGORY, FINAL_STAGE_STATUS, TRIM(VARIETY_ABBR) AS VARIETY_ABBR, SKU, WEEK_BUCKET, WEEK_BUCKET_NUM,
    TRIM(PACK_ABBR) AS PACK_ABBR, TRIM(GRADE_ABBR) AS GRADE_ABBR, TRIM(SIZE_ABBR) AS SIZE_ABBR, TRIM(POOL) AS POOL, "Process Code",
    GROWER_NUMBER, TRIM(PALLET_TR_CODE) AS PALLET_TR_CODE, PALLET_TICKET, "CROP_YEAR",
    SUM(CARTONS) AS CARTONS, SUM(EQ_ON_HAND) AS EQ_ON_HAND, SUM(CARTONS_AVAIL) AS CARTONS_AVAIL
  FROM FROSTY.STAGING.DQ_EQ_WITH_KEYS03
  WHERE CARTONS_AVAIL > 0 AND GROUP_CATEGORY IN ('AP', 'OA', 'CH', 'OC')
  GROUP BY GROUP_CATEGORY, FINAL_STAGE_STATUS, VARIETY_ABBR, SKU, WEEK_BUCKET, WEEK_BUCKET_NUM,
           PACK_ABBR, GRADE_ABBR, SIZE_ABBR, POOL, "Process Code",
           GROWER_NUMBER, PALLET_TR_CODE, PALLET_TICKET, "CROP_YEAR"
),
pallet_source AS (
  SELECT
    PALLET_TICKET,
    SUM(CASE WHEN UPPER(TRIM(PALLET_TR_CODE)) = 'R' THEN CARTONS ELSE 0 END) AS NET_CARTONS_R,
    SUM(CASE WHEN UPPER(TRIM(PALLET_TR_CODE)) = 'P' THEN CARTONS ELSE 0 END) AS NET_CARTONS_P
  FROM inv_base
  GROUP BY PALLET_TICKET
),
pallet_class AS (
  SELECT
    PALLET_TICKET,
    CASE
      WHEN NET_CARTONS_R >= NET_CARTONS_P AND NET_CARTONS_R > 0 THEN 'FROM REPACK'
      ELSE 'FROM PRODUCTION'
    END AS PALLET_SOURCE_FLAG
  FROM pallet_source
)
SELECT
  b.GROUP_CATEGORY, b.FINAL_STAGE_STATUS, b.VARIETY_ABBR, b.SKU, b.WEEK_BUCKET, b.WEEK_BUCKET_NUM,
  b.PACK_ABBR, b.GRADE_ABBR, b.SIZE_ABBR, b.POOL, b."Process Code",
  b.GROWER_NUMBER, b.PALLET_TR_CODE, b.PALLET_TICKET, b."CROP_YEAR",
  pc.PALLET_SOURCE_FLAG,
  CASE
    WHEN pc.PALLET_SOURCE_FLAG = 'FROM PRODUCTION' THEN 'Production'
    ELSE 'Repack'
  END AS RUN_TYPE,
  b.CARTONS, b.EQ_ON_HAND, b.CARTONS_AVAIL
FROM inv_base b
JOIN pallet_class pc ON b.PALLET_TICKET = pc.PALLET_TICKET;
