-- Daily carton snapshot at EQ grain. Source: VW_DB2_MSTRT_ORIGINAL_PACKDATE_PROCESS_STAGE_REPORT_SKU_ALLCARTONS_2_EQ.
-- Adds SOURCE (pallet-source), GROWER, POOL. Includes AP, OA, CH, OC. Refresh once daily (demanding query).
CREATE OR REPLACE DYNAMIC TABLE FROSTY.DBT_DEV_DBT_DEV.DT_CARTON_DAILY_SNAPSHOT_EQ(
  DATE,
  GROUP_CATEGORY,
  CROP_YEAR,
  VARIETY_ABBR,
  PACK_ABBR,
  SIZE_ABBR,
  SPECIAL_INV,
  REPORT_GROUP,
  GROWER_NUMBER,
  POOL,
  SOURCE,
  ON_HAND_END_OF_DAY,
  ON_HAND_END_OF_DAY_EQ,
  AVG_AGE_ON_HAND_DAYS,
  PACKED_THAT_DAY,
  PACKED_THAT_DAY_EQ,
  SHIPPED_THAT_DAY_NET,
  SHIPPED_THAT_DAY_NET_EQ,
  AVG_AGE_SHIPPED_DAYS
) target_lag = '1 day' refresh_mode = AUTO initialize = ON_SCHEDULE warehouse = CT_WH
AS
WITH base AS (
  SELECT
    *,
    COALESCE(
      TRY_TO_DATE(LAST_UPDATE_2, 'YYYYMMDD'),
      TRY_TO_DATE(LAST_UPDATE_2),
      PACK_DATE_FORMATTED
    ) AS event_dt
  FROM FROSTY.STAGING.VW_DB2_MSTRT_ORIGINAL_PACKDATE_PROCESS_STAGE_REPORT_SKU_ALLCARTONS_2_EQ
  WHERE GROUP_CATEGORY IN ('AP', 'OA', 'CH', 'OC')
    AND CROP_YEAR IN (2023, 2024, 2025, 2026)
),
pallet_source AS (
  SELECT
    PALLET_TICKET,
    CASE
      WHEN SUM(CASE WHEN UPPER(TRIM(PALLET_TR_CODE)) = 'R' THEN COALESCE(CARTONS, 0) ELSE 0 END)
           >= SUM(CASE WHEN UPPER(TRIM(PALLET_TR_CODE)) = 'P' THEN COALESCE(CARTONS, 0) ELSE 0 END)
           AND SUM(CASE WHEN UPPER(TRIM(PALLET_TR_CODE)) = 'R' THEN COALESCE(CARTONS, 0) ELSE 0 END) > 0
        THEN 'FROM REPACK'
      ELSE 'FROM PRODUCTION'
    END AS SOURCE
  FROM base
  GROUP BY PALLET_TICKET
),
dates AS (
  SELECT DATEADD(day, SEQ4(), '2023-01-01'::date) AS snapshot_date
  FROM TABLE(GENERATOR(ROWCOUNT => 2000))
  WHERE snapshot_date <= CURRENT_DATE
),
events_asof AS (
  SELECT d.snapshot_date, b.*
  FROM dates d
  JOIN base b ON b.event_dt <= d.snapshot_date
),
latest_asof AS (
  SELECT e.*, ps.SOURCE AS pallet_source
  FROM (
    SELECT
      snapshot_date,
      PALLET_TICKET,
      GROUP_CATEGORY,
      CROP_YEAR,
      VARIETY_ABBR,
      PACK_ABBR,
      SIZE_ABBR,
      SPECIAL_INV,
      GROWER_NUMBER,
      POOL,
      ON_HAND_CARTON,
      CARTONS_AVAIL,
      COALESCE(EQ_ON_HAND, ON_HAND_CARTON * COALESCE(VWEQFC, 1))::NUMBER(18,4) AS EQ_VAL,
      PACK_DATE_FORMATTED AS ORIGINAL_PACK_DATE_FORMATTED,
      ROW_NUMBER() OVER (PARTITION BY snapshot_date, PALLET_TICKET
                         ORDER BY event_dt DESC, SEQ_NUMBER DESC) AS rn
    FROM events_asof
  ) e
  JOIN pallet_source ps ON ps.PALLET_TICKET = e.PALLET_TICKET
  WHERE e.rn = 1
),
daily_on_hand AS (
  SELECT
    snapshot_date AS DATE,
    GROUP_CATEGORY,
    CROP_YEAR,
    VARIETY_ABBR,
    PACK_ABBR,
    SIZE_ABBR,
    SPECIAL_INV,
    CASE WHEN PACK_ABBR IN ('W2PA','W2RA','W3EA','W3PA','W3RA','W5EA','W5RA','WEUA','WR3A','WRPA')
         THEN 'Walmart' ELSE 'Not Walmart' END AS REPORT_GROUP,
    TRIM(COALESCE(GROWER_NUMBER, '')) AS GROWER_NUMBER,
    TRIM(COALESCE(POOL, '')) AS POOL,
    pallet_source AS SOURCE,

    SUM(GREATEST(
      CASE
        WHEN snapshot_date = CURRENT_DATE THEN CARTONS_AVAIL
        ELSE ON_HAND_CARTON
      END, 0)) AS ON_HAND_END_OF_DAY,

    SUM(GREATEST(EQ_VAL, 0)) AS ON_HAND_END_OF_DAY_EQ,

    SUM(GREATEST(
      CASE
        WHEN snapshot_date = CURRENT_DATE THEN CARTONS_AVAIL
        ELSE ON_HAND_CARTON
      END, 0)
      * DATEDIFF('day', ORIGINAL_PACK_DATE_FORMATTED, snapshot_date))
      / NULLIF(SUM(GREATEST(CASE WHEN snapshot_date = CURRENT_DATE THEN CARTONS_AVAIL ELSE ON_HAND_CARTON END, 0)), 0)
      AS AVG_AGE_ON_HAND_DAYS,

    SUM(GREATEST(EQ_VAL, 0) * DATEDIFF('day', ORIGINAL_PACK_DATE_FORMATTED, snapshot_date))
      / NULLIF(SUM(GREATEST(EQ_VAL, 0)), 0) AS AVG_AGE_ON_HAND_DAYS_EQ

  FROM latest_asof
  GROUP BY snapshot_date, GROUP_CATEGORY, CROP_YEAR, VARIETY_ABBR, PACK_ABBR, SIZE_ABBR, SPECIAL_INV,
           GROWER_NUMBER, POOL, pallet_source
),
daily_flows AS (
  SELECT
    event_dt AS DATE,
    GROUP_CATEGORY,
    CROP_YEAR,
    VARIETY_ABBR,
    PACK_ABBR,
    SIZE_ABBR,
    SPECIAL_INV,
    CASE WHEN PACK_ABBR IN ('W2PA','W2RA','W3EA','W3PA','W3RA','W5EA','W5RA','WEUA','WR3A','WRPA')
         THEN 'Walmart' ELSE 'Not Walmart' END AS REPORT_GROUP,
    TRIM(COALESCE(GROWER_NUMBER, '')) AS GROWER_NUMBER,
    TRIM(COALESCE(POOL, '')) AS POOL,
    ps.SOURCE,

    SUM(CASE WHEN PALLET_TR_CODE IN ('P','R') THEN COALESCE(CARTONS, 0) ELSE 0 END) AS PACKED_THAT_DAY,
    SUM(CASE WHEN PALLET_TR_CODE IN ('P','R') THEN COALESCE(CARTONS, 0) * COALESCE(VWEQFC, 1) ELSE 0 END) AS PACKED_THAT_DAY_EQ,
    SUM(CASE WHEN PALLET_TR_CODE = 'S' THEN CARTONS ELSE 0 END) AS SHIPPED_THAT_DAY_NET,
    SUM(CASE WHEN PALLET_TR_CODE = 'S' THEN CARTONS * COALESCE(VWEQFC, 1) ELSE 0 END) AS SHIPPED_THAT_DAY_NET_EQ,
    SUM(ABS(CARTONS) * DATEDIFF('day', PACK_DATE_FORMATTED, event_dt))
      / NULLIF(SUM(ABS(CARTONS)), 0) AS AVG_AGE_SHIPPED_DAYS
  FROM base
  JOIN pallet_source ps ON ps.PALLET_TICKET = base.PALLET_TICKET
  WHERE PACK_DATE_FORMATTED IS NOT NULL
  GROUP BY event_dt, GROUP_CATEGORY, CROP_YEAR, VARIETY_ABBR, PACK_ABBR, SIZE_ABBR, SPECIAL_INV,
           GROWER_NUMBER, POOL, ps.SOURCE
)
SELECT
  COALESCE(o.DATE, f.DATE) AS DATE,
  COALESCE(o.GROUP_CATEGORY, f.GROUP_CATEGORY) AS GROUP_CATEGORY,
  COALESCE(o.CROP_YEAR, f.CROP_YEAR) AS CROP_YEAR,
  COALESCE(o.VARIETY_ABBR, f.VARIETY_ABBR) AS VARIETY_ABBR,
  COALESCE(o.PACK_ABBR, f.PACK_ABBR) AS PACK_ABBR,
  COALESCE(o.SIZE_ABBR, f.SIZE_ABBR) AS SIZE_ABBR,
  COALESCE(o.SPECIAL_INV, f.SPECIAL_INV) AS SPECIAL_INV,
  COALESCE(o.REPORT_GROUP, f.REPORT_GROUP) AS REPORT_GROUP,
  COALESCE(o.GROWER_NUMBER, f.GROWER_NUMBER) AS GROWER_NUMBER,
  COALESCE(o.POOL, f.POOL) AS POOL,
  COALESCE(o.SOURCE, f.SOURCE) AS SOURCE,

  COALESCE(o.ON_HAND_END_OF_DAY, 0) AS ON_HAND_END_OF_DAY,
  COALESCE(o.ON_HAND_END_OF_DAY_EQ, 0) AS ON_HAND_END_OF_DAY_EQ,
  o.AVG_AGE_ON_HAND_DAYS,
  COALESCE(f.PACKED_THAT_DAY, 0) AS PACKED_THAT_DAY,
  COALESCE(f.PACKED_THAT_DAY_EQ, 0) AS PACKED_THAT_DAY_EQ,
  COALESCE(f.SHIPPED_THAT_DAY_NET, 0) AS SHIPPED_THAT_DAY_NET,
  COALESCE(f.SHIPPED_THAT_DAY_NET_EQ, 0) AS SHIPPED_THAT_DAY_NET_EQ,
  f.AVG_AGE_SHIPPED_DAYS

FROM daily_on_hand o
FULL OUTER JOIN daily_flows f
  ON f.DATE = o.DATE
 AND f.GROUP_CATEGORY = o.GROUP_CATEGORY
 AND f.CROP_YEAR = o.CROP_YEAR
 AND f.VARIETY_ABBR = o.VARIETY_ABBR
 AND f.PACK_ABBR = o.PACK_ABBR
 AND f.SIZE_ABBR = o.SIZE_ABBR
 AND f.SPECIAL_INV = o.SPECIAL_INV
 AND f.REPORT_GROUP = o.REPORT_GROUP
 AND f.GROWER_NUMBER = o.GROWER_NUMBER
 AND f.POOL = o.POOL
 AND f.SOURCE = o.SOURCE;
